# Generated by Django 5.2.1 on 2025-05-14 19:24

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("individualizacion", "Individualización"),
                            ("bandas criminales", "Bandas Criminales"),
                            ("conflictividad barrial", "Conflictividad Barrial"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiarioDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("url_principal", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="UsuarioSistema",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LinkRelevante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("categorias", models.ManyToManyField(blank=True, to="app.categoria")),
                (
                    "diario_digital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="app.diariodigital",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Articulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("fecha_generacion", models.DateTimeField(auto_now_add=True)),
                (
                    "generado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articulos_generados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("links_incluidos", models.ManyToManyField(to="app.linkrelevante")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("prensa", "Encargado de Prensa"),
                            ("clasificacion", "Encargado de Clasificación"),
                            ("redaccion", "Encargado de Redacción"),
                            ("publicacion", "Encargado de Publicación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
