# Generated by Django 5.2.1 on 2025-05-15 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de sesión"),
                            ("logout", "Cierre de sesión"),
                            ("carga_link", "Carga de Link"),
                            ("cambio_estado", "Cambio de Estado"),
                            ("clic_link", "Clic en Link"),
                            ("creacion_articulo", "Creación de Artículo"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
