# Generated by Django 4.2.1 on 2025-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_actividad"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UsuarioSistema",
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
