# Generated by Django 4.2.1 on 2025-05-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_delete_usuariosistema_alter_categoria_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkrelevante",
            name="diario_digital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.diariodigital",
            ),
        ),
    ]
