# Generated by Django 4.2.1 on 2025-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_linkrelevante_diario_digital"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividad",
            options={"ordering": ["-fecha_hora"], "verbose_name_plural": "Actividades"},
        ),
        migrations.AlterModelOptions(
            name="articulo",
            options={
                "ordering": ["-fecha_generacion"],
                "verbose_name_plural": "Artículos",
            },
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name_plural": "Categorías"},
        ),
        migrations.AlterModelOptions(
            name="linkrelevante",
            options={
                "ordering": ["-fecha_carga"],
                "verbose_name_plural": "Links Relevantes",
            },
        ),
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("logout", "Cierre de sesión"),
                    ("carga_link", "Carga de Link"),
                    ("cambio_estado", "Cambio de Estado"),
                    ("clic_link", "Clic en Link"),
                    ("creacion_articulo", "Creación de Artículo"),
                    ("clasificacion_link", "Clasificación de Link (Categorías)"),
                    ("otro", "Otro"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="links_incluidos",
            field=models.ManyToManyField(
                related_name="articulos", to="app.linkrelevante"
            ),
        ),
        migrations.AlterField(
            model_name="linkrelevante",
            name="categorias",
            field=models.ManyToManyField(
                blank=True, related_name="links", to="app.categoria"
            ),
        ),
    ]
