# Generated by Django 4.2.1 on 2025-06-26 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0005_alter_actividad_options_alter_articulo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeIndividual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apellido_nombre", models.CharField(max_length=200)),
                ("alias", models.CharField(blank=True, max_length=100, null=True)),
                ("documento", models.CharField(blank=True, max_length=50, null=True)),
                ("cuit", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("edad", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "nacionalidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("domicilio", models.TextField(blank=True, null=True)),
                ("actividad", models.TextField(blank=True, null=True)),
                (
                    "rol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soldadito", "Soldadito"),
                            ("sicario", "Sicario"),
                            ("lugarteniente", "Lugarteniente"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("banda", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "situacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("libertad", "Libertad"),
                            ("fallecido", "Fallecido"),
                            ("detenido", "Detenido"),
                            ("domiciliaria", "Domiciliaria"),
                            ("profugo", "Prófugo"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("hechos_destacados", models.TextField(blank=True, null=True)),
                ("fecha_hecho", models.DateField(blank=True, null=True)),
                (
                    "lugar_hecho",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("vehiculos", models.TextField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "articulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="app.articulo",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
