# Generated by Django 4.2.1 on 2025-06-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_informeindividual"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informeindividual",
            name="articulo",
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="articulos",
            field=models.ManyToManyField(
                related_name="informes_individuales", to="app.articulo"
            ),
        ),
    ]
