# Generated by Django 4.2.1 on 2025-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_informeindividual_articulo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="diariodigital",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Carga la imagen del logo del diario. Se recomienda un tamaño pequeño (ej. 30x30px).",
                null=True,
                upload_to="logos/",
            ),
        ),
    ]
