# Generated by Django 4.2.1 on 2025-07-04 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_diariodigital_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Domicilio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calle", models.CharField(blank=True, max_length=200)),
                ("altura", models.CharField(blank=True, max_length=50)),
                ("barrio", models.CharField(blank=True, max_length=100)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("provincia", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Empleador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("cuit", models.CharField(max_length=11)),
                ("fecha_alta", models.DateField()),
                ("fecha_baja", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HechoDestacado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("lugar", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
                ("dominio", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Vinculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_apellido", models.CharField(max_length=200)),
                ("dni", models.CharField(max_length=8)),
                ("tipo", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name="articulo",
            options={
                "ordering": ["-fecha_creacion"],
                "verbose_name_plural": "Artículos",
            },
        ),
        migrations.RenameField(
            model_name="articulo",
            old_name="fecha_generacion",
            new_name="fecha_creacion",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="cuit",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="edad",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="fecha_hecho",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="hechos_destacados",
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="lugar_hecho",
        ),
        migrations.AddField(
            model_name="articulo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.categoria",
            ),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="linkrelevante",
            name="revisado_clasificador",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linkrelevante",
            name="revisado_editor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="actividad",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="alias",
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="articulos",
            field=models.ManyToManyField(blank=True, to="app.articulo"),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="banda",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="documento",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="nacionalidad",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="rol",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="situacion",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="telefono",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="vehiculos",
        ),
        migrations.AddField(
            model_name="articulo",
            name="hechos_destacados",
            field=models.ManyToManyField(blank=True, to="app.hechodestacado"),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="empleadores",
            field=models.ManyToManyField(blank=True, to="app.empleador"),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="vinculos",
            field=models.ManyToManyField(blank=True, to="app.vinculo"),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="alias",
            field=models.ManyToManyField(blank=True, to="app.alias"),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="domicilio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.domicilio",
            ),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="vehiculos",
            field=models.ManyToManyField(blank=True, to="app.vehiculo"),
        ),
    ]
