# Generated by Django 4.2.1 on 2025-07-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkrelevante",
            name="revisado_redactor",
            field=models.BooleanField(default=False),
        ),
    ]
