# Generated by Django 4.2.1 on 2025-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_linkrelevante_revisado_redactor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informeindividual",
            name="apellido_nombre",
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="apellido",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="nombre",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
