# Generated by Django 4.2.1 on 2025-07-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_informeindividual_apellido_nombre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="revisado_redactor",
            field=models.BooleanField(default=False),
        ),
    ]
