# Generated by Django 4.2.1 on 2025-07-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_articulo_revisado_redactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Telefono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="informeindividual",
            name="telefono",
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="telefono",
            field=models.ManyToManyField(blank=True, to="app.telefono"),
        ),
    ]
