# Generated by Django 4.2.1 on 2025-07-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_telefono_remove_informeindividual_telefono_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informeindividual",
            name="domicilio",
        ),
        migrations.AddField(
            model_name="informeindividual",
            name="domicilio",
            field=models.ManyToManyField(blank=True, to="app.domicilio"),
        ),
    ]
