# Generated by Django 4.2.1 on 2025-07-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_remove_informeindividual_domicilio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informeindividual",
            name="rol",
            field=models.CharField(
                choices=[
                    ("soldadito", "Soldadito"),
                    ("sicario", "Sicario"),
                    ("lugarteniente", "Lugarteniente"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="situacion",
            field=models.CharField(
                choices=[
                    ("libertad", "Libertad"),
                    ("fallecido", "Fallecido"),
                    ("detenido", "Detenido"),
                    ("domiciliaria", "Domiciliaria"),
                    ("profugo", "Prófugo"),
                ],
                max_length=20,
            ),
        ),
    ]
