# Generated by Django 4.2.1 on 2025-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_alter_informeindividual_rol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informeindividual",
            name="cuit",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
