# Generated by Django 4.2.1 on 2025-07-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_informeindividual_cuit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("logout", "Cierre de sesión"),
                    ("carga_link", "Carga de Link"),
                    ("cambio_estado", "Cambio de Estado"),
                    ("clic_link", "Clic en Link"),
                    ("creacion_articulo", "Creación de Artículo"),
                    ("carge_informe", "carga de informe"),
                    ("otro", "Otro"),
                ],
                max_length=30,
            ),
        ),
    ]
