# Generated by Django 4.2.1 on 2025-07-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_alter_actividad_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informeindividual",
            name="rol",
            field=models.CharField(
                choices=[
                    ("soldadito", "Soldadito"),
                    ("sicario", "Sicario"),
                    ("lugarteniente", "Lugarteniente"),
                    ("lider", "Lider"),
                ],
                max_length=20,
            ),
        ),
    ]
