# Generated by Django 4.2.1 on 2025-07-06 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0019_alter_informeindividual_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="informeindividual",
            name="generado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informes_generados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
