# Generated by Django 4.2.1 on 2025-07-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_alter_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiculo",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
