# Generated by Django 4.2.1 on 2025-07-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_vehiculo_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domicilio",
            name="altura",
            field=models.IntegerField(blank=True),
        ),
    ]
