# Generated by Django 4.2.1 on 2025-07-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_alter_domicilio_altura"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleador",
            name="cuit",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="informeindividual",
            name="cuit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
