# Generated by Django 4.2.1 on 2025-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_alter_empleador_cuit_alter_informeindividual_cuit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vinculo",
            name="dni",
            field=models.IntegerField(blank=True),
        ),
    ]
