# Generated by Django 4.2.1 on 2025-07-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_vinculo_dni"),
    ]

    operations = [
        migrations.AddField(
            model_name="informeindividual",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Sube una foto relacionada con el informe.",
                null=True,
                upload_to="fotos_informes/",
            ),
        ),
    ]
