# Generated by Django 4.2.1 on 2025-09-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_solicitudinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudinfo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
