# Generated by Django 4.2.1 on 2025-09-27 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_alter_solicitudinfo_id"),
        ("app", "0030_herramientaosint"),
    ]

    operations = []
