# Generated by Django 4.2.1 on 2025-09-27 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_merge_20250927_1811"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herramientaosint",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
