# Generated by Django 4.2.1 on 2025-09-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_herramientaosint_tipo"),
        ("app", "0032_alter_herramientaosint_id"),
    ]

    operations = []
