# Generated by Django 4.2.1 on 2025-09-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_hechocriminal"),
        ("app", "0033_merge_20250927_1828"),
    ]

    operations = []
