# Generated by Django 4.2.1 on 2025-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_merge_0032_hechocriminal_0033_merge_20250927_1828"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hechocriminal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
