# Generated by Django 4.2.1 on 2025-09-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_bandacriminal"),
        ("app", "0035_alter_hechocriminal_id"),
    ]

    operations = []
