# Generated by Django 4.2.1 on 2025-09-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_merge_0033_bandacriminal_0035_alter_hechocriminal_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandacriminal",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
