# Generated by Django 4.2.1 on 2025-09-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0034_hechocriminal_campos"),
        ("app", "0037_alter_bandacriminal_id"),
    ]

    operations = []
