# Generated by Django 4.2.1 on 2025-09-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_redsocial_tvdigital_radiodigital"),
        ("app", "0038_merge_20250927_1917"),
    ]

    operations = []
