# Generated by Django 4.2.1 on 2025-09-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_merge_20250927_1932"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiodigital",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="redsocial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="tvdigital",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
