# Generated by Django 4.2.1 on 2025-10-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_hechocriminal_creado_por"),
        ("app", "0040_alter_radiodigital_id_alter_redsocial_id_and_more"),
    ]

    operations = []
