# Generated by Django 4.2.1 on 2025-10-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_merge_20251002_1539"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hechocriminal",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("robo", "Robo"),
                    ("homicidio", "Homicidio"),
                    ("duelo_de_espadas", "Duelo de espadas"),
                    ("desamor", "Desamor"),
                    ("tristeza", "Tristeza"),
                    ("venta_de_organos", "Venta de organos"),
                    ("duelo_de_baile", "Duelo de baile"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
