# Generated by Django 4.2.1 on 2025-10-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_alter_hechocriminal_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkrelevante",
            name="red_social",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="links",
                to="app.redsocial",
            ),
        ),
    ]

