# Generated by Django 4.2.1 on 2025-10-02 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def move_red_social_links(apps, schema_editor):
    LinkRelevante = apps.get_model("app", "LinkRelevante")
    LinkRedSocial = apps.get_model("app", "LinkRedSocial")

    links = LinkRelevante.objects.exclude(red_social=None)
    for link in links.iterator():
        social_link = LinkRedSocial.objects.create(
            url=link.url,
            fecha_carga=link.fecha_carga,
            cargado_por=link.cargado_por,
            red_social=link.red_social,
            estado=link.estado,
            fecha_aprobacion=link.fecha_aprobacion,
            revisado_clasificador=link.revisado_clasificador,
            revisado_editor=link.revisado_editor,
            revisado_redactor=link.revisado_redactor,
        )
        social_link.fecha_carga = link.fecha_carga
        social_link.save(update_fields=["fecha_carga"])
        social_link.categorias.set(link.categorias.all())
        link.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_linkrelevante_red_social"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkRedSocial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(unique=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(choices=[("pendiente", "Pendiente"), ("aprobado", "Aprobado"), ("descartado", "Descartado")], default="pendiente", max_length=20)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("revisado_clasificador", models.BooleanField(default=False)),
                ("revisado_editor", models.BooleanField(default=False)),
                ("revisado_redactor", models.BooleanField(default=False)),
                ("cargado_por", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="links_red_social_cargados", to=settings.AUTH_USER_MODEL)),
                ("categorias", models.ManyToManyField(blank=True, related_name="links_red_social", to="app.categoria")),
                ("red_social", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="links", to="app.redsocial")),
            ],
            options={
                "verbose_name": "Link de Red Social",
                "verbose_name_plural": "Links de Redes Sociales",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.RunPython(move_red_social_links, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="linkrelevante",
            name="red_social",
        ),
    ]
