# Generated by Django 4.2.1 on 2025-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_split_red_social_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linkredsocial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
