# Generated by Django 4.2.1 on 2025-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_alter_linkredsocial_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en redaccion", "En redacción"),
                    ("pendiente de informacion", "Pendiente de información"),
                    ("completo", "Completo"),
                ],
                default="en redaccion",
                max_length=30,
            ),
        ),
    ]
