# Generated by Django 4.2.1 on 2025-10-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_articulo_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="categoria_principal",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
