# Generated by Django 4.2.1 on 2025-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_articulo_categoria_principal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articulo",
            name="categoria_principal",
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="lugar",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="articulo",
            name="solicitudes_info",
            field=models.ManyToManyField(
                related_name="articulos", to="app.solicitudinfo"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="categoria",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
