# Generated by Django 4.2.1 on 2025-10-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_remove_articulo_categoria_principal_articulo_fecha_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="aprobacion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_aprobado_por_redaccion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_generado_por_redaccion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_leido_por_prensa",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_leido_por_redaccion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="articulo",
            name="fecha_redactado_por_prensa",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
