# Generated by Django 4.2.1 on 2025-10-09 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_articulo_aprobacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.categoria",
            ),
        ),
    ]
