# Generated by Django 4.2.1 on 2025-10-30 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0053_hechodelictivo_articulo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkTvDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("revisado_clasificador", models.BooleanField(default=False)),
                ("revisado_editor", models.BooleanField(default=False)),
                ("revisado_redactor", models.BooleanField(default=False)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_tv_digital_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True, related_name="links_tv_digital", to="app.categoria"
                    ),
                ),
                (
                    "tv_digital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="app.tvdigital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link de TV Digital",
                "verbose_name_plural": "Links de TV Digital",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="LinkRadioDigital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado", "Aprobado"),
                            ("descartado", "Descartado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("revisado_clasificador", models.BooleanField(default=False)),
                ("revisado_editor", models.BooleanField(default=False)),
                ("revisado_redactor", models.BooleanField(default=False)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_radio_digital_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="links_radio_digital",
                        to="app.categoria",
                    ),
                ),
                (
                    "radio_digital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="links",
                        to="app.radiodigital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link de Radio Digital",
                "verbose_name_plural": "Links de Radio Digital",
                "ordering": ["-fecha_carga"],
            },
        ),
    ]
