# Generated by Django 4.2.1 on 2025-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_hechodelictivo_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha_hecho',
            field=models.DateField(blank=True, help_text='Fecha en que ocurrió el hecho', null=True, verbose_name='Fecha del Hecho'),
        ),
    ]
