# Generated by Django 4.2.1 on 2025-11-18 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_articulo_fecha_hecho"),
        ("app", "0054_linktvdigital_linkradiodigital"),
    ]

    operations = []
