# Generated by Django 4.2.1 on 2025-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_merge_20251118_0935"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bandacriminal",
            options={
                "ordering": ["nombres"],
                "verbose_name": "Banda Criminal",
                "verbose_name_plural": "Bandas Criminales",
            },
        ),
        migrations.AlterField(
            model_name="bandacriminal",
            name="nombre",
            field=models.CharField(db_column="nombre", max_length=150, unique=True),
        ),
        migrations.RenameField(
            model_name="bandacriminal",
            old_name="nombre",
            new_name="nombres",
        ),
        migrations.RemoveField(
            model_name="bandacriminal",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="bandacriminal",
            name="hechos",
        ),
        migrations.RemoveField(
            model_name="bandacriminal",
            name="integrantes",
        ),
        migrations.AddField(
            model_name="bandacriminal",
            name="lideres",
            field=models.ManyToManyField(
                blank=True, related_name="bandas_lideradas", to="app.informeindividual"
            ),
        ),
        migrations.AddField(
            model_name="bandacriminal",
            name="miembros",
            field=models.ManyToManyField(
                blank=True, related_name="bandas_miembro", to="app.informeindividual"
            ),
        ),
        migrations.AddField(
            model_name="bandacriminal",
            name="territorio_operacion",
            field=models.CharField(default="-", max_length=255),
            preserve_default=False,
        ),
    ]
