# Generated by Django 4.2.1 on 2025-11-18 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_zonas_influencia"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "app_bandacriminal_bandas_aliadas" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "from_bandacriminal_id" bigint NOT NULL REFERENCES "app_bandacriminal" ("id") DEFERRABLE INITIALLY DEFERRED,
                "to_bandacriminal_id" bigint NOT NULL REFERENCES "app_bandacriminal" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE TABLE IF NOT EXISTS "app_bandacriminal_bandas_rivales" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "from_bandacriminal_id" bigint NOT NULL REFERENCES "app_bandacriminal" ("id") DEFERRABLE INITIALLY DEFERRED,
                "to_bandacriminal_id" bigint NOT NULL REFERENCES "app_bandacriminal" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "app_bandacriminal_bandas_aliadas_from_bandacriminal_id_to_bandacriminal_id_18025d94_uniq"
                ON "app_bandacriminal_bandas_aliadas" ("from_bandacriminal_id", "to_bandacriminal_id");
            CREATE INDEX IF NOT EXISTS "app_bandacriminal_bandas_aliadas_from_bandacriminal_id_04518059"
                ON "app_bandacriminal_bandas_aliadas" ("from_bandacriminal_id");
            CREATE INDEX IF NOT EXISTS "app_bandacriminal_bandas_aliadas_to_bandacriminal_id_8ea7d6cc"
                ON "app_bandacriminal_bandas_aliadas" ("to_bandacriminal_id");
            CREATE UNIQUE INDEX IF NOT EXISTS "app_bandacriminal_bandas_rivales_from_bandacriminal_id_to_bandacriminal_id_bdf0b6fb_uniq"
                ON "app_bandacriminal_bandas_rivales" ("from_bandacriminal_id", "to_bandacriminal_id");
            CREATE INDEX IF NOT EXISTS "app_bandacriminal_bandas_rivales_from_bandacriminal_id_b8b77cb0"
                ON "app_bandacriminal_bandas_rivales" ("from_bandacriminal_id");
            CREATE INDEX IF NOT EXISTS "app_bandacriminal_bandas_rivales_to_bandacriminal_id_c4cc40b1"
                ON "app_bandacriminal_bandas_rivales" ("to_bandacriminal_id");
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_rivales_to_bandacriminal_id_c4cc40b1";
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_rivales_from_bandacriminal_id_b8b77cb0";
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_rivales_from_bandacriminal_id_to_bandacriminal_id_bdf0b6fb_uniq";
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_aliadas_to_bandacriminal_id_8ea7d6cc";
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_aliadas_from_bandacriminal_id_04518059";
            DROP INDEX IF EXISTS "app_bandacriminal_bandas_aliadas_from_bandacriminal_id_to_bandacriminal_id_18025d94_uniq";
            DROP TABLE IF EXISTS "app_bandacriminal_bandas_rivales";
            DROP TABLE IF EXISTS "app_bandacriminal_bandas_aliadas";
            """,
        ),
    ]
