# Generated by Django 4.2.1 on 2025-11-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_recreate_banda_relations"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeBandaCriminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resumen_ejecutivo",
                    models.TextField(
                        blank=True,
                        help_text="Resumen redactado por el equipo encargado del informe.",
                    ),
                ),
                (
                    "zonas_influencia",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Listado estructurado de zonas donde opera la banda en el contexto del informe.",
                    ),
                ),
                (
                    "conclusion_relevante",
                    models.TextField(
                        blank=True,
                        help_text="Conclusión redactada por el redactor responsable.",
                    ),
                ),
                (
                    "posible_evolucion",
                    models.TextField(
                        blank=True,
                        help_text="Hipótesis u observaciones sobre la evolución de la banda.",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "banda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informes",
                        to="app.bandacriminal",
                    ),
                ),
                (
                    "bandas_aliadas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="informes_bandas_aliadas",
                        to="app.bandacriminal",
                    ),
                ),
                (
                    "bandas_rivales",
                    models.ManyToManyField(
                        blank=True,
                        related_name="informes_bandas_rivales",
                        to="app.bandacriminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de Banda Criminal",
                "verbose_name_plural": "Informes de Bandas Criminales",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="JerarquiaPrincipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("lider", "Líder"),
                            ("lugarteniente", "Lugarteniente"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jerarquias",
                        to="app.informebandacriminal",
                    ),
                ),
                (
                    "miembro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jerarquias_de_banda",
                        to="app.informeindividual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jerarquía Principal",
                "verbose_name_plural": "Jerarquías Principales",
                "unique_together": {("informe", "miembro")},
            },
        ),
        migrations.AddField(
            model_name="informebandacriminal",
            name="jerarquias_principales",
            field=models.ManyToManyField(
                blank=True,
                related_name="informes_banda_criminal",
                through="app.JerarquiaPrincipal",
                to="app.informeindividual",
            ),
        ),
    ]
