# Generated by Django 4.2.1 on 2025-11-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_informebandacriminal_jerarquiaprincipal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hechodelictivo",
            name="autor_desconocido",
            field=models.BooleanField(
                default=False,
                help_text="Marcá esta opción si no hay autores identificados.",
            ),
        ),
    ]
