# Generated by Django 4.2.1 on 2025-11-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_hechodelictivo_autor_desconocido"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informebandacriminal",
            name="resumen_ejecutivo",
        ),
    ]
