# Generated by Django 4.2.1 on 2025-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_remove_informebandacriminal_resumen_ejecutivo"),
    ]

    operations = [
        migrations.AddField(
            model_name="informebandacriminal",
            name="introduccion_descripcion",
            field=models.TextField(
                blank=True, help_text="Descripción de la introducción del informe."
            ),
        ),
    ]
