# Generated by Django 4.2.1 on 2025-11-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_informebandacriminal_introduccion_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="hechodelictivo",
            name="bandas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bandas criminales relacionadas con el hecho.",
                related_name="hechos_delictivos",
                to="app.bandacriminal",
            ),
        ),
    ]
