# Generated by Django 4.2.1 on 2025-11-18 23:31

import json
from django.db import migrations, models


def ubicacion_char_a_json(apps, schema_editor):
    Hecho = apps.get_model("app", "HechoDelictivo")
    for hecho in Hecho.objects.all():
        valor = hecho.ubicacion
        if isinstance(valor, str):
            data = {
                "barrio": "",
                "localidad": "",
                "ciudad": valor,
                "provincia": "",
            }
            hecho.ubicacion = json.dumps(data, ensure_ascii=False)
            hecho.save(update_fields=["ubicacion"])


def ubicacion_json_a_char(apps, schema_editor):
    Hecho = apps.get_model("app", "HechoDelictivo")
    for hecho in Hecho.objects.all():
        valor = hecho.ubicacion
        if isinstance(valor, str):
            try:
                valor = json.loads(valor)
            except json.JSONDecodeError:
                text = valor
            else:
                partes = [
                    valor.get("barrio", ""),
                    valor.get("localidad", ""),
                    valor.get("ciudad", ""),
                    valor.get("provincia", ""),
                ]
                text = ", ".join([p for p in partes if p])
        elif isinstance(valor, dict):
            partes = [
                valor.get("barrio", ""),
                valor.get("localidad", ""),
                valor.get("ciudad", ""),
                valor.get("provincia", ""),
            ]
            text = ", ".join([p for p in partes if p])
        else:
            text = ""
        hecho.ubicacion = text
        hecho.save(update_fields=["ubicacion"])


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_hechodelictivo_bandas"),
    ]

    operations = [
        migrations.RunPython(ubicacion_char_a_json, ubicacion_json_a_char),
        migrations.AlterField(
            model_name="hechodelictivo",
            name="ubicacion",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detalle de ubicación con barrio, localidad, ciudad y provincia.",
            ),
        ),
    ]
