# Generated by Django 4.2.1 on 2025-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_alter_hechodelictivo_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="informebandacriminal",
            name="antecedentes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de antecedentes personalizados que incluye título y descripción.",
            ),
        ),
    ]
