# Generated by Django 4.2.1 on 2025-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_informebandacriminal_antecedentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="informebandacriminal",
            name="desarrollo_contenido",
            field=models.TextField(
                blank=True,
                help_text="Contenido redactado manualmente para el desarrollo.",
            ),
        ),
        migrations.AddField(
            model_name="informebandacriminal",
            name="desarrollo_titulo",
            field=models.CharField(
                blank=True,
                help_text="Título del apartado de desarrollo.",
                max_length=255,
            ),
        ),
    ]
