# Generated by Django 4.2.1 on 2025-11-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_informebandacriminal_desarrollo_contenido_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informebandacriminal",
            name="conclusiones_desarrollo",
            field=models.TextField(
                blank=True, help_text="Contenido del anexo de conclusiones."
            ),
        ),
    ]
