# Generated by Django 4.2.1 on 2025-11-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0068_informebandacriminal_conclusiones_desarrollo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sarcasmo_mode", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuración del Sistema",
            },
        ),
    ]
