# Generated by Django 4.2.1 on 2025-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0069_configuracionsistema"),
    ]

    operations = [
        migrations.AddField(
            model_name="informebandacriminal",
            name="exportaciones",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
