# Generated by Django 4.2.1 on 2025-11-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0070_informebandacriminal_exportaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="informeindividual",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                ],
                help_text="Sexo registrado en el documento del individuo.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("login", "Inicio de sesión"),
                    ("logout", "Cierre de sesión"),
                    ("carga_link", "Carga de Link"),
                    ("cambio_estado", "Cambio de Estado"),
                    ("clic_link", "Clic en Link"),
                    ("creacion_articulo", "Creación de Artículo"),
                    ("clasificacion_link", "Clasificacion del Link"),
                    ("carge_informe", "carga de informe"),
                    ("otro", "Otro"),
                    ("exportar_informe_banda", "Exportó informe de banda"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="hechodelictivo",
            name="ubicacion",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detalle de ubicación con calle, número, barrio, localidad, ciudad y provincia.",
            ),
        ),
    ]
