# Generated by Django 4.2.1 on 2025-11-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_informeindividual_sexo_alter_actividad_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informebandacriminal",
            name="banda",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="informes",
                to="app.bandacriminal",
            ),
        ),
    ]
