# Generated by Django 4.2.1 on 2025-07-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0072_alter_informebandacriminal_banda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("prensa", "Encargado de Prensa"),
                    ("clasificacion", "Encargado de Clasificación"),
                    ("redaccion", "Encargado de Redacción"),
                    ("informes", "Encargado de Informes"),
                    ("gerente", "Encargado de gerencia"),
                    ("gerente_produccion", "Gerente de Producción"),
                    ("observador", "Observador"),
                    ("Cliente", "Cliente"),
                ],
                max_length=20,
            ),
        ),
    ]
