# Generated by Django 4.2.1 on 2025-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkrelevante",
            name="clasificado_por_ia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="linkrelevante",
            name="confianza_clasificacion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="linkrelevante",
            name="resumen_ia",
            field=models.TextField(blank=True),
        ),
    ]
