# Generated by Django 4.2.1 on 2025-12-02 18:20

from django.db import migrations, models


def forward_update_roles(apps, schema_editor):
    UserProfile = apps.get_model("app", "UserProfile")
    UserProfile.objects.filter(rol="observador").update(rol="clasificadorIA")


def backward_update_roles(apps, schema_editor):
    UserProfile = apps.get_model("app", "UserProfile")
    UserProfile.objects.filter(rol="clasificadorIA").update(rol="observador")


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_alter_userprofile_rol"),
    ]

    operations = [
        migrations.RunPython(forward_update_roles, backward_update_roles),
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("prensa", "Encargado de Prensa"),
                    ("clasificacion", "Encargado de Clasificación"),
                    ("redaccion", "Encargado de Redacción"),
                    ("redactor_ia", "Redactor IA"),
                    ("informes", "Encargado de Informes"),
                    ("gerente", "Encargado de gerencia"),
                    ("gerente_produccion", "Gerente de Producción"),
                    ("clasificadorIA", "Clasificador IA"),
                    ("Cliente", "Cliente"),
                ],
                max_length=20,
            ),
        ),
    ]
