# Generated by Django 4.2.1 on 2025-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_alter_userprofile_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudinfo",
            name="documentacion",
            field=models.FileField(
                blank=True,
                help_text="Adjuntá documentación relacionada en PDF, Word o imagen.",
                null=True,
                upload_to="solicitudes_documentacion/",
            ),
        ),
    ]
