# Generated by Django 4.2.1 on 2025-12-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_solicitudinfo_documentacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudinfo",
            name="documentacion",
            field=models.FileField(
                blank=True,
                help_text="Adjuntá documentación relacionada en formato PDF, Word o imagen.",
                null=True,
                upload_to="solicitudes_documentacion/",
            ),
        ),
    ]
