# Generated by Django 4.2.1 on 2025-12-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_bandacriminal_nombre_alias"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bandacriminal",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Banda Criminal",
                "verbose_name_plural": "Bandas Criminales",
            },
        ),
    ]
