# Generated by Django 4.2.1 on 2025-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0081_alter_bandacriminal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandacriminal",
            name="links_aprobados_diario",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links de diarios digitales aprobados asociados a la banda.",
                related_name="bandas_relacionadas_diario",
                to="app.linkrelevante",
            ),
        ),
        migrations.AddField(
            model_name="bandacriminal",
            name="links_aprobados_red_social",
            field=models.ManyToManyField(
                blank=True,
                help_text="Links de redes sociales aprobados asociados a la banda.",
                related_name="bandas_relacionadas_red",
                to="app.linkredsocial",
            ),
        ),
    ]
