# Generated by Django 4.2.1 on 2025-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0083_rename_informes_role_to_editor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("prensa", "Encargado de Prensa"),
                    ("clasificacion", "Encargado de Clasificación"),
                    ("redaccion", "Encargado de Redacción"),
                    ("editor", "Editor"),
                    ("redactor_ia", "Redactor IA"),
                    ("gerente", "Encargado de gerencia"),
                    ("gerente_produccion", "Gerente de Producción"),
                    ("clasificadorIA", "Clasificador IA"),
                    ("Cliente", "Cliente"),
                ],
                max_length=20,
            ),
        ),
    ]
